import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
test('reaction reels load on demand and close with focus restored',async({page})=>{await page.route('https://www.instagram.com/**',route=>route.fulfill({contentType:'text/html',body:'<html lang="en"><title>Reel test</title><body>Instagram player stub</body></html>'}));await page.goto('/');await expect(page.locator('#reactions .reaction-card')).toHaveCount(6);await expect(page.locator('#reactions iframe')).toHaveCount(0);const trigger=page.getByRole('button',{name:'Play Reaction 01 on Instagram',exact:true});await trigger.click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.reaction-dialog iframe')).toHaveAttribute('src','https://www.instagram.com/reel/DG534zkinXv/embed/');await expect(page.getByRole('link',{name:'Player unavailable? Watch on Instagram'})).toHaveAttribute('href','https://www.instagram.com/reel/DG534zkinXv/');await page.keyboard.press('Escape');await expect(page.locator('#reactions iframe')).toHaveCount(0);await expect(trigger).toBeFocused()});

test('hero starts automatically even while hovered and explicit pause stops it',async({page})=>{
 await page.emulateMedia({reducedMotion:'no-preference'});await page.route('**/video/hero.mp4',route=>route.abort());await page.clock.install();await page.goto('/');
 await expect(page.locator('.hero-carousel')).toHaveAttribute('data-playing','true');await page.locator('.hero-copy').hover();await page.clock.fastForward(11_000);await expect(page.locator('.hero-counter')).not.toHaveText('01 / 03');
 await page.getByRole('button',{name:'Pause slideshow',exact:true}).click();const slide=await page.locator('.hero-counter').textContent();await page.clock.fastForward(15_000);await expect(page.locator('.hero-counter')).toHaveText(slide!);
 await page.getByRole('button',{name:'Play slideshow',exact:true}).click();await page.clock.fastForward(11_000);await expect(page.locator('.hero-counter')).not.toHaveText(slide!);
});
test('reduced motion offers an explicit play override',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.clock.install();await page.goto('/');await expect(page.locator('.hero-carousel')).toHaveAttribute('data-playing','false');await page.getByRole('button',{name:'Play slideshow',exact:true}).click();await page.clock.fastForward(11_000);await expect(page.locator('.hero-counter')).not.toHaveText('01 / 03')});
test('merch switches views and carries the selected item into an enquiry',async({page})=>{await page.goto('/shop/');await page.getByRole('button',{name:'Show back of Lyrical Monster Hoodie'}).click();await expect(page.getByAltText('Lyrical Monster Hoodie — back artwork')).toBeVisible();await page.locator('.merch-card').first().getByRole('link',{name:'ENQUIRE'}).click();await expect(page.getByLabel('What do you have in mind?')).toHaveValue('Merch enquiry');await expect(page.getByLabel('Piece')).toHaveValue('Lyrical Monster Hoodie')});
test('booking validates, prepares a review, and preserves fields on edit',async({page})=>{await page.goto('/book/');await page.getByRole('button',{name:/REVIEW ENQUIRY/}).click();await expect(page.locator('.booking-review')).toHaveCount(0);await page.getByLabel('Your name').fill('Test Promoter');await page.getByLabel('Email *',{exact:true}).fill('promoter@example.com');await page.getByLabel('Phone / WhatsApp').fill('+234 800 000 0000');await page.getByLabel('Venue / location').fill('Example venue');await page.getByLabel('City *',{exact:true}).fill('Lagos');await page.getByLabel('Country').fill('Nigeria');await page.getByLabel('Tell us more').fill('A live performance enquiry & an after-show conversation.');await page.getByRole('button',{name:/REVIEW ENQUIRY/}).click();await expect(page.getByRole('heading',{name:'Ready when you are.'})).toBeFocused();await expect(page.locator('.booking-review pre')).toContainText('Test Promoter');await expect(page.locator('.booking-review pre')).toContainText('performance enquiry');const wa=await page.getByRole('link',{name:'CONTINUE ON WHATSAPP'}).getAttribute('href');expect(new URL(wa!).pathname).toBe('/12407148161');expect(new URL(wa!).searchParams.get('text')).toContain('performance enquiry & an after-show conversation.');const mail=await page.getByRole('link',{name:'OPEN EMAIL'}).getAttribute('href');expect(new URL(mail!).pathname).toBe('090vi@gmail.com');expect(new URL(mail!).searchParams.get('body')).toContain('Test Promoter');await page.getByRole('button',{name:/EDIT DETAILS/}).click();await expect(page.getByLabel('Your name')).toHaveValue('Test Promoter')});
test('experience pages have no serious accessibility violations',async({page})=>{test.setTimeout(120_000);await page.emulateMedia({reducedMotion:'reduce'});for(const width of [375,1440])for(const route of ['/','/book/','/shop/','/visuals/']){await page.setViewportSize({width,height:900});await page.goto(route);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),`${route} at ${width}`).toEqual([])}});
test('hero and merch fit phone and desktop screens',async({page})=>{test.setTimeout(60_000);fs.mkdirSync('tests/visual/experience-final',{recursive:true});await page.emulateMedia({reducedMotion:'reduce'});for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});await page.goto('/');await page.screenshot({path:`tests/visual/experience-final/home-${width}.png`});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#reactions').screenshot({path:"tests/visual/experience-final/reactions-"+width+'.png'});await page.locator('.listen-band').screenshot({path:"tests/visual/experience-final/streaming-"+width+'.png'});await page.locator('#merch').scrollIntoViewIfNeeded();await page.locator('#merch img').first().evaluate((img:HTMLImageElement)=>img.decode());await page.screenshot({path:`tests/visual/experience-final/merch-${width}.png`});await page.goto('/book/');await page.screenshot({path:`tests/visual/experience-final/booking-${width}.png`});}});
