import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
const routes=['/','/music/','/music/anike/','/visuals/','/story/','/live/','/gallery/','/press/','/book/','/shop/','/vault/','/does-not-exist/'];

test('home communicates the artist and owner-supplied materials',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{level:1,name:'090VI'})).toBeVisible();await expect(page.getByText('Beyond the obvious',{exact:true})).toBeVisible();await expect(page.getByText('ANIKE',{exact:true}).first()).toBeVisible();await expect(page.getByText('NO DATES ANNOUNCED')).toBeVisible();});
test('menu opens, traps focus, and closes with Escape',async({page})=>{await page.goto('/');const menu=page.getByRole('button',{name:'MENU'});await menu.focus();await menu.press('Enter');await expect(page.getByRole('navigation',{name:'Main navigation'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'MENU'})).toBeFocused();});
test('gallery dialog opens and restores trigger focus',async({page})=>{await page.goto('/gallery/');const image=page.getByRole('button',{name:/View image:/}).first();await image.click();await expect(page.getByRole('dialog',{name:'Gallery image'})).toBeVisible();await page.keyboard.press('Escape');await expect(image).toBeFocused();});
test('booking does not claim to submit without an endpoint',async({page})=>{await page.goto('/book/');await expect(page.getByText(/Booking email not configured/)).toBeVisible();});
test('story is an editorial page and does not embed the source PDF',async({page})=>{await page.goto('/story/');await expect(page.getByRole('heading',{level:1,name:/Beyond the obvious/})).toBeVisible();await expect(page.getByRole('heading',{name:'A story in motion.'})).toBeVisible();await expect(page.locator('iframe')).toHaveCount(0);await expect(page.getByRole('link',{name:/Step into the music/i})).toBeVisible();});
test('unknown route exports the designed 404',async({page})=>{const response=await page.goto('/does-not-exist/');expect(response?.status()).toBe(404);await expect(page.getByText('YOU GOT LOST')).toBeVisible();});
for(const route of routes)for(const width of [375,1440])test(`axe ${route} at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await page.goto(route);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();const violations=results.violations.filter(v=>['critical','serious'].includes(v.impact??''));expect(violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,foreground:n.any[0]?.data?.fgColor,background:n.any[0]?.data?.bgColor}))}))).toEqual([])});
test('responsive screenshot matrix',async({page})=>{test.setTimeout(180_000);fs.mkdirSync('tests/visual/out',{recursive:true});const widths=[320,375,390,414,768,1024,1280,1440,1920,2560];for(const route of routes)for(const width of widths){await page.setViewportSize({width,height:900});await page.goto(route);await page.evaluate(async()=>{const images=[...document.images];for(const image of images)image.loading='eager';await Promise.all(images.map(image=>image.decode().catch(()=>undefined)))});const safe=route==='/'?'home':route.replaceAll('/','_');await page.screenshot({path:`tests/visual/out/${safe}-${width}.png`})}});
