'use client';
import {type CSSProperties,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {heroSlides} from '../../data/hero-slides';
import {useMotion} from '../../hooks/useMotion';
export function HeroCarousel(){const [index,setIndex]=useState(0);const [paused,setPaused]=useState(false);const [interacting,setInteracting]=useState(false);const [videoReady,setVideoReady]=useState(false);const [videoFailed,setVideoFailed]=useState(false);const [enhanced,setEnhanced]=useState(false);const [resourceLimited,setResourceLimited]=useState(false);const [inView,setInView]=useState(true);const root=useRef<HTMLElement>(null);const video=useRef<HTMLVideoElement>(null);const timer=useRef<{kill:()=>void}|null>(null);const previous=useRef(0);const touch=useRef<{x:number;y:number}|null>(null);const {mode}=useMotion();const current=heroSlides[index]!;const motionAllowed=mode==='full'&&!resourceLimited;const autoPaused=paused||interacting;
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const connection=(navigator as Navigator&{connection?:{saveData?:boolean;effectiveType?:string}}).connection;const memory=(navigator as Navigator&{deviceMemory?:number}).deviceMemory;setResourceLimited(Boolean(connection?.saveData||['2g','slow-2g','3g'].includes(connection?.effectiveType??'')||(memory!==undefined&&memory<=2)));setEnhanced(true)});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{const node=root.current;const observer=new IntersectionObserver(entries=>{const active=entries[0]?.isIntersecting??true;setInView(active);if(!active)video.current?.pause()},{threshold:.1});if(node)observer.observe(node);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!enhanced||autoPaused||!inView||!motionAllowed||heroSlides.length<2||document.hidden)return;let disposed=false;let tween:{kill:()=>void}|undefined;const rootElement=root.current;const go=()=>{if(disposed)return;setIndex(i=>(i+1)%heroSlides.length)};const init=async()=>{const {gsap}=await import('gsap');if(disposed)return;const cap=current.maxDurationMs??10_000;const delay=current.video?(videoReady&&!videoFailed?Math.min(video.current?.duration?video.current.duration*1000:cap,cap):6500):6500;tween=gsap.delayedCall(delay/1000,go);timer.current=tween;if(rootElement)rootElement.dataset.timerReady='true'};void init();const visibility=()=>{if(document.hidden){timer.current?.kill();video.current?.pause()}else if(!autoPaused&&inView&&motionAllowed)void init()};document.addEventListener('visibilitychange',visibility);return()=>{disposed=true;tween?.kill();if(rootElement)delete rootElement.dataset.timerReady;document.removeEventListener('visibilitychange',visibility)}},[index,autoPaused,inView,motionAllowed,videoReady,videoFailed,enhanced,current]);
 useEffect(()=>{if(!enhanced||index!==0||!inView||!motionAllowed)return;const idle=window.requestIdleCallback??((cb:IdleRequestCallback)=>window.setTimeout(cb,800));const cancel=window.cancelIdleCallback??window.clearTimeout;const id=idle(()=>{const el=video.current;if(!el)return;el.preload='auto';const fail=window.setTimeout(()=>setVideoFailed(true),3000);void el.play().then(()=>{window.clearTimeout(fail);setVideoReady(true)}).catch(()=>{window.clearTimeout(fail);setVideoFailed(true)})});return()=>cancel(id as number)},[enhanced,index,inView,motionAllowed]);
 useEffect(()=>{const el=video.current;if(!el)return;if(index!==0||autoPaused||!inView||document.hidden||mode==='reduced'){el.pause();if(index!==0)el.currentTime=0}},[index,autoPaused,inView,mode]);
 useEffect(()=>{if(index===previous.current)return;previous.current=index;if(!motionAllowed)return;let disposed=false;let animation:{kill:()=>void}|undefined;const play=async()=>{const {gsap}=await import('gsap');if(disposed)return;const media=document.querySelector<HTMLElement>('.hero-slide .hero-still');if(!media)return;const timeline=gsap.timeline();animation=timeline;timeline.fromTo(media,{clipPath:'inset(100% 0 0 0)',scale:1.12,opacity:0},{clipPath:'inset(0% 0 0 0)',scale:1.04,opacity:1,duration:1.1,ease:'power4.inOut'});timeline.to(media,{scale:1.12,duration:6.5,ease:'sine.inOut'})};void play();return()=>{disposed=true;animation?.kill()}},[index,motionAllowed]);
 function step(n:number){timer.current?.kill();setIndex(i=>(i+n+heroSlides.length)%heroSlides.length);setPaused(false)}
 return <section ref={root} className="hero hero-carousel" aria-roledescription="carousel" aria-label="090VI featured visuals" onMouseEnter={()=>setInteracting(true)} onMouseLeave={()=>setInteracting(false)} onFocusCapture={()=>setInteracting(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setInteracting(false)}} onTouchStart={e=>{const p=e.touches.item(0);if(p)touch.current={x:p.clientX,y:p.clientY}}} onTouchEnd={e=>{if(!touch.current)return;const p=e.changedTouches.item(0);if(p){const dx=p.clientX-touch.current.x,dy=p.clientY-touch.current.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))step(dx<0?1:-1)}touch.current=null}} onKeyDown={e=>{if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1)}} tabIndex={0}>
  <div className="hero-slides" aria-live={autoPaused||mode==='reduced'?'polite':'off'}><div className="hero-slide" role="group" aria-roledescription="slide" aria-label={`${index+1} of ${heroSlides.length}`} key={current.id}><picture className="hero-picture"><source type="image/avif" srcSet={`/images/responsive/${current.id==='portrait'?'artist-hero2':'artist-hero'}-480.avif 480w, /images/responsive/${current.id==='portrait'?'artist-hero2':'artist-hero'}-768.avif 768w, /images/responsive/${current.id==='portrait'?'artist-hero2':'artist-hero'}-1080.avif 1080w`} sizes="100vw"/><source type="image/webp" srcSet={`/images/responsive/${current.id==='portrait'?'artist-hero2':'artist-hero'}-480.webp 480w, /images/responsive/${current.id==='portrait'?'artist-hero2':'artist-hero'}-768.webp 768w, /images/responsive/${current.id==='portrait'?'artist-hero2':'artist-hero'}-1080.webp 1080w`} sizes="100vw"/><img className="hero-still" src={current.image} alt={current.alt} width="1400" height="872" fetchPriority={index===0?'high':'auto'} loading={index===0?'eager':'lazy'} decoding="async" style={{objectPosition:current.position}} onError={()=>{if(current.id==='portrait')step(1)}}/></picture>{current.video&&!videoFailed&&<video ref={video} className={videoReady?'hero-video ready':'hero-video'} muted playsInline preload="none" poster={current.image} aria-hidden="true" disablePictureInPicture onEnded={()=>step(1)} onError={()=>setVideoFailed(true)}><source src={current.video} type="video/mp4"/></video>}</div></div>
  <div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">LAGOS · AFROPOP</p><h1>090VI</h1><p className="tagline">Beyond the obvious</p><Link className="round-link" href="#music" aria-label="Explore music">↓</Link></div><span className="side-note">INDEPENDENT SOUND · 01—∞</span>
  {enhanced&&heroSlides.length>1&&<div className="hero-controls" aria-label="Slideshow controls"><button className="hero-arrow" aria-label="Previous slide" onClick={()=>step(-1)}>‹</button><button className="hero-pause" aria-label={paused?'Play slideshow':'Pause slideshow'} aria-pressed={paused} onClick={()=>setPaused(v=>!v)}>{paused?'PLAY':'PAUSE'}</button><span className="hero-counter">{String(index+1).padStart(2,'0')} / {String(heroSlides.length).padStart(2,'0')}</span><div className="hero-progress" style={{'--slide-duration':current.video?'10s':'6.5s'} as CSSProperties}>{heroSlides.map((slide,i)=><button key={slide.id} aria-label={`Go to slide ${i+1} of ${heroSlides.length}`} aria-current={index===i?'true':undefined} onClick={()=>{timer.current?.kill();setIndex(i);setPaused(true)}}><span/></button>)}</div><button className="hero-arrow" aria-label="Next slide" onClick={()=>step(1)}>›</button></div>}
 </section>
}
