'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {heroSlides} from '../../data/hero-slides';
import {useMotion} from '../../hooks/useMotion';
const initialIndex=Math.max(0,heroSlides.findIndex(slide=>slide.id==='film'&&slide.image==='/images/artist/hero.jpg'));
export function HeroCarousel(){
 const [index,setIndex]=useState(initialIndex),[paused,setPaused]=useState(false),[manualPlay,setManualPlay]=useState(false),[initialImageReady,setInitialImageReady]=useState(false);
 const [videoReady,setVideoReady]=useState(false),[videoFailed,setVideoFailed]=useState(false);
 const [inView,setInView]=useState(true),[tabVisible,setTabVisible]=useState(true),[saveData,setSaveData]=useState(false);
 const root=useRef<HTMLElement>(null),video=useRef<HTMLVideoElement>(null),touch=useRef<{x:number;y:number}|null>(null);
 const {mode}=useMotion();const current=heroSlides[index]!;
 const playing=!paused&&(mode==='full'||manualPlay);const running=playing&&inView&&tabVisible;
 function step(n:number){setIndex(i=>(i+n+heroSlides.length)%heroSlides.length);setVideoReady(false)}
 useEffect(()=>{const update=()=>setTabVisible(!document.hidden);document.addEventListener('visibilitychange',update);const observer=new IntersectionObserver(entries=>setInView(entries[0]?.isIntersecting??true),{threshold:.1});if(root.current)observer.observe(root.current);const frame=requestAnimationFrame(()=>{update();const c=(navigator as Navigator&{connection?:{saveData?:boolean;effectiveType?:string}}).connection;setSaveData(Boolean(c?.saveData||['2g','slow-2g'].includes(c?.effectiveType??'')))});return()=>{cancelAnimationFrame(frame);observer.disconnect();document.removeEventListener('visibilitychange',update)}},[]);
 useEffect(()=>{if(!running||(index===initialIndex&&!initialImageReady))return;const element=root.current;if(element)element.dataset.timerReady='true';const timer=window.setTimeout(()=>{setIndex(i=>(i+1)%heroSlides.length);setVideoReady(false)},current.video&&!videoFailed&&!saveData?10_000:6500);return()=>{clearTimeout(timer);if(element)delete element.dataset.timerReady}},[index,running,current.video,videoFailed,saveData,initialImageReady]);
 useEffect(()=>{const el=video.current;if(!el)return;if(!running||saveData||mode==='reduced'){el.pause();return}let cancelled=false;const timer=window.setTimeout(()=>{if(!cancelled)setVideoFailed(true)},3500);el.muted=true;void el.play().then(()=>{clearTimeout(timer);if(!cancelled)setVideoReady(true)}).catch(()=>{clearTimeout(timer);if(!cancelled)setVideoFailed(true)});return()=>{cancelled=true;clearTimeout(timer);el.pause()}},[index,running,saveData,mode]);
 const phrases=[['Sound without borders.','From Lagos, with feeling.'],['A voice of his own.','For the moments that stay with you.'],['Beyond the obvious.','Let the rhythm lead you somewhere new.']];
 return <section ref={root} className="hero hero-carousel" aria-roledescription="carousel" aria-label="090VI featured visuals" data-playing={running} tabIndex={0} onTouchStart={e=>{const p=e.touches.item(0);if(p)touch.current={x:p.clientX,y:p.clientY}}} onTouchEnd={e=>{const p=e.changedTouches.item(0);if(p&&touch.current){const dx=p.clientX-touch.current.x,dy=p.clientY-touch.current.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))step(dx<0?1:-1)}touch.current=null}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}}}>
  <div className="hero-slides" aria-live={playing?'off':'polite'}><div className="hero-slide" role="group" aria-roledescription="slide" aria-label={`${index+1} of ${heroSlides.length}`} key={current.id}><picture className="hero-picture"><source type="image/avif" srcSet={[480,768,1080,1280].map(w=>`/images/responsive/${current.id==='hero3'?'artist-hero3':'artist-hero'}-${w}.avif ${w}w`).join(', ')} sizes="100vw"/><source type="image/webp" srcSet={[480,768,1080,1280].map(w=>`/images/responsive/${current.id==='hero3'?'artist-hero3':'artist-hero'}-${w}.webp ${w}w`).join(', ')} sizes="100vw"/><img className="hero-still" src={current.image} alt={current.alt} width="1400" height="872" loading="eager" fetchPriority={index===initialIndex?'high':'auto'} decoding="async" sizes="100vw" style={{objectPosition:current.position}} onLoad={()=>{if(index===initialIndex)setInitialImageReady(true)}} onError={()=>{if(current.id==='hero3')step(1)}}/></picture>{current.video&&!videoFailed&&!saveData&&mode==='full'&&<video ref={video} className={videoReady?'hero-video ready':'hero-video'} muted autoPlay playsInline preload="metadata" poster={current.image} aria-hidden="true" disablePictureInPicture onEnded={()=>step(1)} onError={()=>setVideoFailed(true)}><source src={current.video} type="video/mp4"/></video>}</div></div>
  <div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">LAGOS · AFROPOP · 090VI</p><h1>090VI</h1><p className="tagline">Beyond the obvious</p><Link className="hero-listen" href="#music">ENTER THE SOUND <span aria-hidden="true">↗</span></Link></div>
  <div className="hero-poetry" key={`copy-${index}`}><span className="eyebrow">0{index+1} / A WORLD OF HIS OWN</span><p>{phrases[index]![0]}</p><span>{phrases[index]![1]}</span></div>
  <div className="hero-controls" aria-label="Slideshow controls"><button className="hero-arrow" aria-label="Previous slide" onClick={()=>step(-1)}>‹</button><button className="hero-pause" aria-label={playing?'Pause slideshow':'Play slideshow'} aria-pressed={!playing} onClick={()=>{if(playing)setPaused(true);else{setPaused(false);setManualPlay(true)}}}>{playing?'PAUSE':'PLAY'}</button><span className="hero-counter">{String(index+1).padStart(2,'0')} / {String(heroSlides.length).padStart(2,'0')}</span><div className="hero-progress">{heroSlides.map((slide,i)=><button key={slide.id} aria-label={`Go to slide ${i+1} of ${heroSlides.length}`} aria-current={index===i?'true':undefined} onClick={()=>{setIndex(i);setVideoReady(false)}}/>)}</div><button className="hero-arrow" aria-label="Next slide" onClick={()=>step(1)}>›</button></div>
 </section>
}
