'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ErrorBoundary} from './ErrorBoundary';
import {site} from '../data/site.config';
type FrequencyCanvasType=typeof import('./FrequencyCanvas').FrequencyCanvas;
export function Player(){
 const audio=useRef<HTMLAudioElement>(null);const context=useRef<AudioContext|null>(null);
 const [playing,setPlaying]=useState(false);const [position,setPosition]=useState(0);const [duration,setDuration]=useState(0);const [volume,setVolume]=useState(1);const [muted,setMuted]=useState(false);const [analyser,setAnalyser]=useState<AnalyserNode|null>(null);const [FrequencyCanvas,setFrequencyCanvas]=useState<FrequencyCanvasType|null>(null);
 const fmt=(v:number)=>`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`;
 const toggle=useCallback(async()=>{if(!audio.current)return;if(audio.current.paused){try{if(site.features.frequencyEngine&&!context.current&&'AudioContext'in window){const ctx=new AudioContext();const node=ctx.createMediaElementSource(audio.current);const meter=ctx.createAnalyser();meter.fftSize=256;node.connect(meter);meter.connect(ctx.destination);context.current=ctx;setAnalyser(meter)}await context.current?.resume();await audio.current.play();setPlaying(true);if(site.features.frequencyEngine&&!FrequencyCanvas)void import('./FrequencyCanvas').then(module=>setFrequencyCanvas(()=>module.FrequencyCanvas)).catch(()=>{})}catch{setPlaying(false)}}else{audio.current.pause();setPlaying(false)}},[FrequencyCanvas]);
 useEffect(()=>{if(!('mediaSession'in navigator)||!('MediaMetadata'in window))return;navigator.mediaSession.metadata=new MediaMetadata({title:'ANIKE',artist:'090VI',album:'Preview'});navigator.mediaSession.setActionHandler('play',()=>{void toggle()});navigator.mediaSession.setActionHandler('pause',()=>{audio.current?.pause();setPlaying(false)});navigator.mediaSession.setActionHandler('seekto',e=>{if(audio.current&&e.seekTime!==undefined)audio.current.currentTime=e.seekTime});return()=>{navigator.mediaSession.setActionHandler('play',null);navigator.mediaSession.setActionHandler('pause',null);navigator.mediaSession.setActionHandler('seekto',null)}},[toggle]);
 return <aside className="persistent-player" aria-label="ANIKE audio preview"><audio ref={audio} preload="none" onTimeUpdate={()=>{if(!audio.current)return;setPosition(audio.current.currentTime);if('mediaSession'in navigator&&Number.isFinite(audio.current.duration))navigator.mediaSession.setPositionState({duration:audio.current.duration,playbackRate:audio.current.playbackRate,position:audio.current.currentTime})}} onLoadedMetadata={()=>audio.current&&setDuration(audio.current.duration)} onEnded={()=>setPlaying(false)}><source src="/audio/previews/Anike.mp3" type="audio/mpeg"/></audio><button aria-label={playing?'Pause ANIKE preview':'Play ANIKE preview'} onClick={()=>void toggle()}>{playing?'Ⅱ':'▶'}</button><span>ANIKE <small>PREVIEW</small></span>{analyser&&FrequencyCanvas&&<ErrorBoundary label="Frequency visualizer"><FrequencyCanvas analyser={analyser} playing={playing}/></ErrorBoundary>}<input aria-label={`Track position ${fmt(position)} of ${fmt(duration)}`} type="range" min="0" max={duration||1} value={Math.min(position,duration||1)} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value)}}/><time>{fmt(position)} / {fmt(duration)}</time><button aria-label={muted?'Unmute':'Mute'} onClick={()=>{if(!audio.current)return;audio.current.muted=!audio.current.muted;setMuted(audio.current.muted)}}>{muted?'UNMUTE':'MUTE'}</button><label className="volume-label"><span className="visually-hidden">Volume</span><input type="range" min="0" max="1" step="0.05" value={volume} aria-label="Volume" onChange={e=>{const v=Number(e.target.value);setVolume(v);if(audio.current)audio.current.volume=v}}/></label></aside>
}
