'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {site} from '../data/site.config';
import {Logo} from './brand/Logo';
const baseEntries:[string,string,string][]=[['Music','/music/','music'],['Visuals','/visuals/','visuals'],['Story','/story/','story'],['Live','/live/','live'],['Gallery','/gallery/','gallery'],['Press','/press/','press'],['Book','/book/','booking']];
export function SiteNav(){const [open,setOpen]=useState(false);const [openedAt,setOpenedAt]=useState('');const trigger=useRef<HTMLButtonElement>(null);const pathname=usePathname();const router=useRouter();const visible=open&&openedAt===pathname;const entries:[string,string][] = baseEntries.filter(([, ,feature])=>site.features[feature as keyof typeof site.features]).map(([name,url])=>[name,url]);if(site.features.shop)entries.push(['Shop','/shop/']);if(site.features.vault)entries.push(['Vault','/vault/']);function close(){setOpen(false);requestAnimationFrame(()=>trigger.current?.focus())}
 useEffect(()=>{if(!visible)return;const prior=document.body.style.overflow;const priorPadding=document.body.style.paddingRight;const width=window.innerWidth-document.documentElement.clientWidth;document.body.style.overflow='hidden';document.body.style.paddingRight=`${width}px`;const main=document.querySelector<HTMLElement>('#main');const footer=document.querySelector<HTMLElement>('body>footer');const player=document.querySelector<HTMLElement>('.persistent-player');if(main)main.inert=true;if(footer)footer.inert=true;if(player)player.inert=true;const links=[...document.querySelectorAll<HTMLElement>('#menu-overlay a[href]:not([tabindex="-1"]), #menu-overlay button:not([disabled])')];links[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){close()}if(e.key==='Tab'){const first=links[0],last=links.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=prior;document.body.style.paddingRight=priorPadding;if(main)main.inert=false;if(footer)footer.inert=false;if(player)player.inert=false;window.removeEventListener('keydown',key)}},[visible]);
 function choose(url:string){setOpen(false);if(url.replace(/\/$/,'')===pathname.replace(/\/$/,'')){window.scrollTo({top:0,behavior:document.documentElement.dataset.motion==='reduced'?'auto':'smooth'});requestAnimationFrame(()=>trigger.current?.focus())}else{router.push(url);requestAnimationFrame(()=>requestAnimationFrame(()=>trigger.current?.focus()))}}
 function toggle(){if(visible){setOpen(false)}else{setOpenedAt(pathname);setOpen(true)}}
 return <><header className="topbar" inert={visible} aria-hidden={visible}><Logo className="brand"/><button ref={trigger} type="button" className="menu-toggle" aria-expanded={visible} aria-controls="menu-overlay" onClick={toggle}>{visible?'CLOSE':'MENU'}</button></header><nav id="menu-overlay" className={`nav-overlay ${visible?'open':''}`} role="dialog" aria-modal="true" aria-label="Site menu" aria-hidden={!visible} inert={!visible}><Logo className="menu-logo" tabIndex={-1}/><ol>{entries.map(([name,url],i)=><li key={url}><a href={url} onClick={e=>{e.preventDefault();choose(url)}}><span>{name}</span><span>0{i+1}</span></a></li>)}</ol><button type="button" className="nav-close" onClick={close}>CLOSE <span aria-hidden="true">×</span></button></nav></>}
