import fs from 'node:fs';import path from 'node:path';import {z} from 'zod';import {releases} from '../data/releases.ts';import {artist} from '../data/artist.ts';import {videos} from '../data/videos.ts';import {gallery} from '../data/gallery.ts';import {events} from '../data/events.ts';import {links} from '../data/links.ts';import {pressFiles} from '../data/press.ts';
import {merch} from '../data/merch.ts';import {reactions} from '../data/reactions.ts';
for(const item of merch)for(const src of [item.front,item.back])if(!fs.existsSync(path.join('public',src)))throw Error(`Missing merch image: ${src}. Run npm run prepare:assets.`);
for(const reaction of reactions){z.object({id:z.string().regex(/^[\w-]+$/),title:z.string().min(1),creator:z.string().optional(),song:z.string().optional(),url:z.url().startsWith('https://www.instagram.com/reel/')}).parse(reaction);if(reaction.url!==`https://www.instagram.com/reel/${reaction.id}/`)throw Error(`Reaction URL does not match its reel id: ${reaction.id}`)}
const ReleaseSchema=z.object({id:z.string().min(1),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),title:z.string().min(1),releaseDate:z.iso.date(),provenance:z.object({verified:z.boolean()}),streaming:z.array(z.object({url:z.url().startsWith('https://')})),artwork:z.object({src:z.string(),alt:z.string().min(1),width:z.number().positive(),height:z.number().positive()}).optional(),audio:z.object({src:z.string(),durationSec:z.number().positive().max(90),kind:z.enum(['preview','full'])}).optional()});
const root=process.cwd();const missing:string[]=[];const exists=(src:string)=>{const file=path.join(root,'public',decodeURIComponent(src.replace(/^\//,'')));if(!fs.existsSync(file)){missing.push(src);return false}return true};const slugs=new Set<string>();for(const r of releases){ReleaseSchema.parse(r);if(slugs.has(r.slug))throw Error(`Duplicate slug: ${r.slug}`);slugs.add(r.slug);if(r.artwork)exists(r.artwork.src);if(r.audio){const file=path.join(root,'public',r.audio.src.replace(/^\//,''));exists(r.audio.src);if(fs.existsSync(file)&&fs.statSync(file).size>1_000_000)throw Error(`Preview is over 1MB: ${r.audio.src}`);if(r.audio.kind==='full')throw Error(`Full-length audio is not enabled in this preview build: ${r.slug}`)}}
for(const image of gallery)exists(image.image.src);for(const video of videos){exists(video.poster.src);if(video.src)exists(video.src)}if(artist.heroImage)exists(artist.heroImage.src);if(artist.portrait)exists(artist.portrait.src);for(const file of pressFiles)exists(file.href);for(const item of links)if(!item.url.startsWith('https://')||item.url.includes('example.'))throw Error(`Invalid supplied link: ${item.url}`);for(const event of events)if(event.ticketUrl&&(!event.ticketUrl.startsWith('https://')||event.ticketUrl.includes('example.')))throw Error(`Invalid event URL: ${event.ticketUrl}`);
const report=`# Content validation report\n\n- ${releases.length} catalogue records; ${releases.filter(r=>!r.provenance.verified).length} are marked unverified.\n- ${videos.length} local visual records and ${gallery.length} gallery assets checked.\n- ${events.length} event records checked.\n- Missing referenced files: ${missing.length?missing.join(', '):'none'}.\n- Supplied outbound links are HTTPS; their official status still requires owner confirmation.\n- Known owner questions and asset provenance: see CONTENT_REPORT.md.\n`;
fs.writeFileSync(path.join(root,'CONTENT_REPORT.generated.md'),report);if(missing.length&&process.argv.includes('--strict'))throw Error(`Missing assets: ${missing.join(', ')}`);console.log(report);
