import type {Metadata} from 'next';
import {getPublishedReleases} from '../../lib/content';

export const metadata:Metadata={title:'Press',description:'Press and artist materials for 090VI.',alternates:{canonical:'/press/'}};
const photos=[['1.jpg','090VI · press photograph 01'],['2.png','090VI · press photograph 02'],['3.jpg','090VI · press photograph 03'],['4.jpg','090VI · press photograph 04'],['5.jpg','090VI · press photograph 05'],['6.jpg','090VI · press photograph 06'],['7.jpg','090VI · press photograph 07'],['8.jpg','090VI · press photograph 08']] as const;
export default function PressPage(){return <section className="section page-section press-room"><p className="eyebrow">090VI / PRESS</p><h1>Press room.</h1><p>Artist materials, brought into the room. Read the story, view the photographs, and find the essentials below.</p>
 <div className="press-documents"><article className="press-document"><div className="press-document-heading"><div><p className="eyebrow">01 / BIOGRAPHY</p><h2>Artist biography</h2></div></div><iframe title="090VI artist biography" src="/press/bio.pdf#toolbar=0&view=FitH" loading="lazy"/></article>
 <article className="press-document"><div className="press-document-heading"><div><p className="eyebrow">02 / STORY</p><h2>Story copy</h2></div></div><iframe title="090VI story copy" src="/press/Story%20Copy.pdf#toolbar=0&view=FitH" loading="lazy"/></article></div>
 <div className="press-photo-heading"><div><p className="eyebrow">03 / PHOTOGRAPHS</p><h2>In the frame.</h2></div><p>Official press photographs supplied with the artist materials.</p></div><div className="press-photo-grid">{photos.map(([src,alt],i)=><figure key={src}><picture><source srcSet={`/images/press/${src.replace(/\.[^.]+$/,'')}.avif`} type="image/avif"/><img src={`/images/press/${src.replace(/\.[^.]+$/,'')}.webp`} alt={alt} loading="lazy" decoding="async"/></picture><figcaption>090VI / PRESS {String(i+1).padStart(2,'0')}</figcaption></figure>)}</div>
 <article className="press-logo"><div><p className="eyebrow">04 / IDENTITY</p><h2>The 090VI mark.</h2><p>Official artist logo supplied for press use.</p></div><picture><source srcSet="/images/press/090vi-logo.avif" type="image/avif"/><img src="/images/press/090vi-logo.webp" alt="090VI official logo" loading="lazy" decoding="async"/></picture></article>
 <div className="press-releases"><p className="eyebrow">SELECTED RELEASES</p><ul>{getPublishedReleases().map(x=><li key={x.id}>{x.title} · {x.releaseDate.slice(0,4)}</li>)}</ul></div><p className="small-note">For interviews and usage enquiries, contact <a href="mailto:090vi@gmail.com">090vi@gmail.com</a>.</p></section>}
